import { type NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";
import { Play } from "@icon-park/react";
import Link from "next/link";
// import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "../utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hangman Online</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-6 bg-gradient-to-r from-cyan-500 to-blue-500">
        <p className="text-sm text-white">197 players online</p>
        <h1 className="text-shadow-md text-center text-4xl font-extrabold text-white">
          HANGMAN
          <br />
          <span className="text-6xl italic text-red-600">ONLINE</span>
        </h1>
        <div className="flex flex-row gap-6">
          <Link href="/start">
            <Button>
              <Play theme="outline" size="20" fill="#fff" />
              <p>Start</p>
            </Button>
          </Link>
          <Link href="/join">
            <Button>
              <Play theme="outline" size="20" fill="#fff" />
              <p>Join</p>
            </Button>
          </Link>
        </div>
      </main>
      <div className="absolute bottom-2 flex w-full flex-row gap-2 text-center font-serif text-sm">
        <p className=" hover:text-shadow-md cursor-pointer font-normal text-white duration-100">
          View on Github
        </p>
      </div>
    </>
  );
};

export default Home;
