import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Input from "../components/Input";
import Typewriter from "../components/Typewriter";

const Start: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hangman Online</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-6 bg-gradient-to-r from-cyan-500 to-blue-500">
        <p className="text-sm text-white">197 players online</p>
        <h1 className="text-shadow-md text-center text-4xl font-extrabold text-white">
          HANGMAN
          <br />
          <span className="text-6xl italic text-red-600">ONLINE</span>
        </h1>
        <Typewriter />
        {/* <p className="text-sm text-white text-opacity-50">Start typing...</p> */}
      </main>
      <div className="absolute bottom-2 flex w-full flex-row items-center justify-center gap-2 text-center font-serif text-sm">
        <Link href="/">
          <p className=" hover:text-shadow-md cursor-pointer font-normal text-white duration-100">
            Go Back
          </p>
        </Link>
        <p className="text-white">◦</p>
        <Link href="https://github.com/sqwyer/hangman-online" target="_blank">
          <p className=" hover:text-shadow-md cursor-pointer font-normal text-white duration-100">
            Github
          </p>
        </Link>
      </div>
    </>
  );
};

export default Start;
